Develop
WildCodeSchool/nantes-js-0320-project3-forope pull request #12
Opened 2020-06-16 07:58 UTC by erwanitwish

2020-06-16 09:04 UTC, KatalinaNadasi commented on src/App.jsx
> +    <ThemeProvider theme={Theme}>
It's better not use MAJ here for Theme

2020-06-16 10:24 UTC, KatalinaNadasi requested changes
Good piece of work, congrats !
Please make pull requests more ofter : every time a piece is finished.
Some little comments
- No french please in variables, alt and so on.
- There is a beautiful mixe of values between px, rem and %. Be careful.
margin, padding, font-size : rem is better because relative and not absolute like px.
width : % is better
see comments for the detail. In case go see on mozilla developper : https://developer.mozilla.org/en-US/docs/Web/CSS/width

When you start using a value (rem rather than px for exemple) use the same untill the end of the file and don't change)

Put your style sheets in a style folder 

thank you for using hooks for state components 👍

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/App.jsx
> +      <div className="App">
You can delete this div which is not usefull anymore. And we don't use className because of styled component :)

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/allTemoignages.jsx
> +
Use "Testimony" as well for the name of your component --> "AllTestimonies". A component's name always begin with a maj in React.

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/article.jsx
> +  margin-left: 3vh;
don't use vh for margin and padding (only for width and height in fact) but **rem**. If you want to use relative you can use % but this can be very confusing.
https://developer.mozilla.org/en-US/docs/Web/CSS/margin

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/article.jsx
> +  font-size: 12px;
Better use rem for font-sizes than px that are not relatives but absolute

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/article.jsx
> +  border: 0.12vh solid white;
don't use vh for borders but px or rem https://developer.mozilla.org/en-US/docs/Web/CSS/border

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/article.jsx
> +  border-radius: 3vh;
same here

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/article.jsx
> +  width: 14px;
Better use % for width, px are ok (but absolute)

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/article.jsx
> +export default function Article() {
Is this a component you will need to reuse later ? If yes pass content as props when you call it instead.

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/bandeauTitre.jsx
> +  margin-bottom: 1vw;
same here --> rem

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/bandeauTitre.jsx
> +  text-decoration: underline;
Reusable component ?

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/bandeauTitre.jsx
> +const SubtitleBandeau = styled.p`
Not french here (banner) please

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/bandeauTitre.jsx
> +const TitleBandeau = styled.h1`
no french :)

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/footer.jsx
> +  margin-top: 3vh;
same here --> rem

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/footer.jsx
> +  padding-top: 1vh;
no vh

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/footer.jsx
> +  margin-right: 35%;
--> rem

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/footer.jsx
> +  padding-top: 1vh;
no vh

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/footer.jsx
> +  width: 34px;
--> %

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/footer.jsx
> +  margin-right: 1vh;
--> rem

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/footer.jsx
> +          <Logo src={circle} alt="logo réseaux sociaux" />
english only please

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/navigation.jsx
> +  margin-right: 3vw;
--> rem

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/navigation.jsx
> +  margin-left: 3vw;
--> rem

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/questionaire.jsx
> +  margin-left: 3vw;
--> rem

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/questionaire.jsx
> +  const handleChange2 = (event) => {
change the name with a more specific name than handleChange2n exemple : handleChangeManager

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/questionaire.jsx
> +                <option value="excellence-oppérationnelle">
opérationnelle with on p

2020-06-16 10:24 UTC, KatalinaNadasi commented on src/components/questionaire.jsx
> +                  Excellence oppérationnelle
same here

2020-06-16 15:21 UTC, ahamel1 approved these changes

2020-06-16 15:29 UTC, ahamel1 approved these changes

2020-06-16 15:29 UTC, ho823 approved these changes

2020-06-16 15:45 UTC, KatalinaNadasi commented on src/components/Footer.jsx
> +  margin-right: 40rem;
Non bloquant : Pourquoi il y a besoin d'un margin aussi élevé ? Ca peut être fait autrement je pense à terme.

2020-06-17 07:04 UTC, ahamel1 commented on src/components/Footer.jsx
> +  margin-right: 40rem;
Oui, j'ai vu ça. On s'occupera de changer cette partie !

2020-06-17 07:25 UTC, KatalinaNadasi approved these changes

2020-06-17 07:25 UTC, merged