Develop
WildCodeSchool/nantes-js-0320-project3-forope pull request #36
Opened 2020-07-10 15:27 UTC by erwanitwish

- Front BO done
- link between front and back for DB done

2020-07-13 13:56 UTC, KatalinaNadasi requested changes

2020-07-13 13:56 UTC, KatalinaNadasi commented on src/components/BackOffice/AwesomeList.jsx
> +  // const [List, setList] = useState([]);
Les commentaires sont à enlever avant de merge sur master, mais c'est plutôt une bonne idée de renvoyer une erreur

2020-07-13 13:56 UTC, KatalinaNadasi commented on src/components/BackOffice/ClientList.jsx
> +  // const [error, setError] = useState();
commentaires à enlever

2020-07-13 15:21 UTC, ahamel1 approved these changes

2020-07-15 07:47 UTC, KatalinaNadasi requested changes
Tout doit être mis en anglais sauf le texte qui est injecté dans les pages et en règle général on ne met jamais d'accents et autre caractère spéciaux dans les clés / label, etc.
Commentaire sur le code à régler : voir commentaire

2020-07-15 07:47 UTC, KatalinaNadasi commented on src/components/BackOffice/AwesomeList.jsx
> +        // setError(err);
Si vous ne l'utilisez pas enlevez le plutôt que de laisser un commentaire. Le mieux est de créer un State error, setError et si il y a une erreur de l'afficher dans votre composant directement

2020-07-15 07:47 UTC, KatalinaNadasi commented on src/components/BackOffice/ClientList.jsx
> +        // setError(err);
pareil ici

2020-07-15 07:47 UTC, KatalinaNadasi commented on src/components/BackOffice/ClientList.jsx
> +                <TableCell align="right">{client.Rôle}</TableCell>
Pas d'accent ni de ¨ ^ ou caractères spéciaux car tout doit être écrit en anglais sauf le texte affiché dans votre app

2020-07-15 07:47 UTC, KatalinaNadasi commented on src/components/BackOffice/ClientList.jsx
> +                <TableCell align="right">{client.Téléphone}</TableCell>
pareil

2020-07-15 12:19 UTC, KatalinaNadasi requested changes

2020-07-15 12:19 UTC, KatalinaNadasi commented on src/data/dataalice.json
> +    "formationmanagement": {
English please 🇬🇧

2020-07-15 12:19 UTC, KatalinaNadasi commented on src/data/dataalice.json
> +  "rh_formation": {
English please 🇬🇧

2020-07-15 12:19 UTC, KatalinaNadasi commented on src/data/dataalice.json
> +    "habilitations": {
English please 🇬🇧

2020-07-15 13:37 UTC, KatalinaNadasi approved these changes

2020-07-15 13:37 UTC, merged